kind = "mobile"
previewPath = "/"
title = "InterviewAce"
version = "1.0.0"
id = "artifacts/interview-ace"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/" ]
localPort = 22694

[services.development]
run = "pnpm --filter @workspace/interview-ace run dev"

[services.production.build]
args = [ "pnpm", "--filter", "@workspace/interview-ace", "run", "build" ]

[services.production.run]
args = [ "pnpm", "--filter", "@workspace/interview-ace", "run", "serve" ]

[services.production.run.env]
PORT = "22694"
BASE_PATH = "/"

[services.production.health.startup]
path = "/"
