export interface PracticeQuestion {
  id: string;
  title: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  tags: string[];
  problemStatement: string;
  approach: string;
  hints: string[];
  timeComplexity: string;
  spaceComplexity: string;
}

export interface PracticeCategory {
  id: string;
  title: string;
  icon: string;
  color: string;
  type: 'dsa' | 'lld';
  questions: PracticeQuestion[];
}

export const DSA_CATEGORIES: PracticeCategory[] = [
  {
    id: 'arrays',
    title: 'Arrays',
    icon: 'grid',
    color: '#3B82F6',
    type: 'dsa',
    questions: [
      {
        id: 'arr-1',
        title: 'Two Sum',
        difficulty: 'Easy',
        tags: ['Array', 'HashMap'],
        problemStatement: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice.',
        approach: 'Use a HashMap to store each number and its index. For each element, check if (target - current) exists in the map. If yes, return the pair of indices. If no, add current to the map. This gives O(N) time.',
        hints: [
          'Think about what complement you need for each number.',
          'A HashMap lets you check if the complement exists in O(1).',
          'Iterate once: check map, then insert — never the other way.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(N)',
      },
      {
        id: 'arr-2',
        title: 'Best Time to Buy and Sell Stock',
        difficulty: 'Easy',
        tags: ['Array', 'Greedy'],
        problemStatement: 'You are given an array prices where prices[i] is the price of a given stock on the ith day. You want to maximize your profit by choosing a single day to buy and a single day to sell in the future. Return the maximum profit you can achieve. Return 0 if no profit is possible.',
        approach: 'Track the minimum price seen so far as you scan left to right. At each day, compute profit = current price - minSoFar. Update the global maxProfit. This single pass gives O(N) time.',
        hints: [
          'You must buy before you sell.',
          'Track the smallest price seen so far as you scan.',
          'At each step, the best profit is current price minus the minimum so far.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(1)',
      },
      {
        id: 'arr-3',
        title: 'Product of Array Except Self',
        difficulty: 'Medium',
        tags: ['Array', 'Prefix Product'],
        problemStatement: 'Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i]. You must write an algorithm that runs in O(N) time and without using the division operation.',
        approach: 'Two-pass approach: First pass computes prefix products (product of all elements to the left). Second pass multiplies by suffix products (product of all elements to the right) in reverse. Store results directly in the output array to achieve O(1) extra space.',
        hints: [
          'answer[i] = product of all elements to the left × product of all elements to the right.',
          'First pass: fill output[i] with product of everything to the left of i.',
          'Second pass (right to left): multiply by running suffix product.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(1) excluding output array',
      },
      {
        id: 'arr-4',
        title: 'Container With Most Water',
        difficulty: 'Medium',
        tags: ['Array', 'Two Pointers'],
        problemStatement: 'You are given an integer array height of length n. Find two lines that together with the x-axis form a container such that the container contains the most water. Return the maximum amount of water a container can store.',
        approach: 'Use two pointers starting at both ends. Area = min(height[left], height[right]) × (right - left). Move the pointer with the smaller height inward — moving the taller one can only decrease the width without potentially increasing the min height.',
        hints: [
          'Start with the widest possible container (two ends).',
          'Moving the shorter side inward is the only way to potentially improve.',
          'Moving the taller side guarantees the area decreases or stays the same.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(1)',
      },
      {
        id: 'arr-5',
        title: 'Trapping Rain Water',
        difficulty: 'Hard',
        tags: ['Array', 'Two Pointers', 'Stack'],
        problemStatement: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
        approach: 'Two-pointer approach: maintain maxLeft and maxRight. The water at any position is min(maxLeft, maxRight) - height[i]. Move the pointer with the smaller max inward. This ensures we always know the bottleneck constraint before computing water.',
        hints: [
          'Water trapped at i = min(maxHeightLeft, maxHeightRight) - height[i].',
          'Two pointers: move the side with the smaller maximum inward.',
          'You only need the minimum of the two sides — if left max is smaller, it determines the water level.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(1)',
      },
    ],
  },
  {
    id: 'strings',
    title: 'Strings',
    icon: 'type',
    color: '#10B981',
    type: 'dsa',
    questions: [
      {
        id: 'str-1',
        title: 'Valid Anagram',
        difficulty: 'Easy',
        tags: ['String', 'HashMap', 'Sorting'],
        problemStatement: 'Given two strings s and t, return true if t is an anagram of s, and false otherwise. An anagram is a word or phrase formed by rearranging the letters of a different word.',
        approach: 'Count character frequencies in s using a HashMap/array of size 26. Then verify t has the same frequencies. Alternatively, sort both strings and compare — but O(N log N) is worse than O(N) with counting.',
        hints: [
          'An anagram has the same character frequencies.',
          'Use a frequency count array of size 26 for lowercase letters.',
          'Increment for s, decrement for t, then check all zeros.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(1) — fixed 26-char alphabet',
      },
      {
        id: 'str-2',
        title: 'Longest Substring Without Repeating Characters',
        difficulty: 'Medium',
        tags: ['String', 'Sliding Window', 'HashMap'],
        problemStatement: 'Given a string s, find the length of the longest substring without repeating characters.',
        approach: 'Sliding window with a HashMap storing each character\'s last seen index. Use left and right pointers. When a duplicate is found within the window, advance left past the duplicate\'s previous position. Track max window size throughout.',
        hints: [
          'Use a sliding window with two pointers.',
          'A HashMap tracks the last index of each character.',
          'When you see a duplicate inside the window, shrink from the left.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(min(N, Alphabet))',
      },
      {
        id: 'str-3',
        title: 'Minimum Window Substring',
        difficulty: 'Hard',
        tags: ['String', 'Sliding Window', 'HashMap'],
        problemStatement: 'Given two strings s and t, return the minimum window substring of s such that every character in t (including duplicates) is included in the window. Return an empty string if no such window exists.',
        approach: 'Sliding window with two frequency maps. Expand the right pointer to include t characters. When all characters of t are covered (track "formed" count), shrink from the left to find the minimum valid window. Track global minimum.',
        hints: [
          'Expand right until window contains all of t.',
          'Then contract left to find the minimum such window.',
          'Track "formed" count: how many unique chars in t have been satisfied.',
        ],
        timeComplexity: 'O(N + M)',
        spaceComplexity: 'O(N + M)',
      },
      {
        id: 'str-4',
        title: 'Group Anagrams',
        difficulty: 'Medium',
        tags: ['String', 'HashMap', 'Sorting'],
        problemStatement: 'Given an array of strings strs, group the anagrams together. You can return the answer in any order.',
        approach: 'For each string, compute a canonical key. Two approaches: (1) Sort each string — sorted strings are the same for anagrams. (2) Use a character count tuple as the key (faster). Group strings by their key in a HashMap.',
        hints: [
          'Anagrams have the same sorted form.',
          'Use sorted string as HashMap key.',
          'For O(N·K) instead of O(N·K log K), use char frequency tuple as key.',
        ],
        timeComplexity: 'O(N·K log K) with sorting',
        spaceComplexity: 'O(N·K)',
      },
    ],
  },
  {
    id: 'linked-list',
    title: 'Linked List',
    icon: 'link',
    color: '#F59E0B',
    type: 'dsa',
    questions: [
      {
        id: 'll-1',
        title: 'Reverse Linked List',
        difficulty: 'Easy',
        tags: ['Linked List', 'Recursion'],
        problemStatement: 'Given the head of a singly linked list, reverse the list, and return the reversed list.',
        approach: 'Iterative: maintain prev (null), curr (head). At each step save next = curr.next, set curr.next = prev, advance prev = curr and curr = next. Return prev when curr is null. Recursive: base case is null or single node, recurse on tail and fix pointers on the way back.',
        hints: [
          'Three variables: prev, curr, next.',
          'Save next before overwriting curr.next.',
          'After the loop, prev is the new head.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(1) iterative, O(N) recursive',
      },
      {
        id: 'll-2',
        title: 'Detect Cycle in Linked List',
        difficulty: 'Easy',
        tags: ['Linked List', 'Two Pointers', "Floyd's Algorithm"],
        problemStatement: 'Given head of a linked list, determine if the linked list has a cycle in it. Return true if there is a cycle, otherwise return false.',
        approach: "Floyd's Tortoise and Hare: slow pointer moves 1 step, fast moves 2. If they meet, cycle exists. If fast reaches null, no cycle. For finding cycle start: after meeting, reset one pointer to head and advance both one step at a time — they meet at the cycle entry.",
        hints: [
          'Fast pointer moves 2 nodes, slow moves 1.',
          'If fast reaches null, there is no cycle.',
          'If fast === slow, a cycle exists.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(1)',
      },
      {
        id: 'll-3',
        title: 'Merge Two Sorted Lists',
        difficulty: 'Easy',
        tags: ['Linked List', 'Recursion'],
        problemStatement: 'You are given the heads of two sorted linked lists list1 and list2. Merge the two lists into one sorted list. Return the head of the merged linked list.',
        approach: 'Use a dummy head node to simplify edge cases. Maintain a current pointer. At each step, compare list1.val and list2.val, attach the smaller node, advance that list pointer. After the loop, attach whichever list still has nodes.',
        hints: [
          'Use a dummy node to avoid special-casing the head.',
          'Compare heads of both lists, pick the smaller.',
          'After one list is exhausted, attach the rest of the other.',
        ],
        timeComplexity: 'O(N + M)',
        spaceComplexity: 'O(1)',
      },
      {
        id: 'll-4',
        title: 'Reorder List',
        difficulty: 'Medium',
        tags: ['Linked List', 'Two Pointers', 'Recursion'],
        problemStatement: 'You are given the head of a singly linked-list: L0 → L1 → ... → Ln. Reorder it to: L0 → Ln → L1 → Ln-1 → L2 → Ln-2 → ... You may not modify the values in the list\'s nodes. Only nodes themselves may be changed.',
        approach: 'Three steps: (1) Find the middle using fast/slow pointers. (2) Reverse the second half. (3) Merge the two halves by alternating nodes from each half.',
        hints: [
          'Find the midpoint using slow/fast pointers.',
          'Reverse the second half in-place.',
          'Merge the two halves alternating: first half node, then second half node.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(1)',
      },
    ],
  },
  {
    id: 'stack-queue',
    title: 'Stack & Queue',
    icon: 'layers',
    color: '#EF4444',
    type: 'dsa',
    questions: [
      {
        id: 'sq-1',
        title: 'Valid Parentheses',
        difficulty: 'Easy',
        tags: ['Stack', 'String'],
        problemStatement: 'Given a string s containing just the characters \'(\', \')\', \'{\', \'}\', \'[\' and \']\', determine if the input string is valid. An input string is valid if: open brackets are closed by the same type, in the correct order, and every close bracket has a corresponding open bracket.',
        approach: 'Push opening brackets onto a stack. When a closing bracket is encountered, check if the top of the stack is the matching opener. If not, return false. After processing all characters, the stack must be empty.',
        hints: [
          'Push open brackets; when you see a closer, peek the stack.',
          'If stack is empty or top doesn\'t match, return false.',
          'At the end, an empty stack means all brackets were matched.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(N)',
      },
      {
        id: 'sq-2',
        title: 'Min Stack',
        difficulty: 'Medium',
        tags: ['Stack', 'Design'],
        problemStatement: 'Design a stack that supports push, pop, top, and retrieving the minimum element in constant time. Implement the MinStack class with all operations running in O(1) time.',
        approach: 'Maintain two stacks: main stack and a min stack. When pushing, also push to min stack if the value is ≤ current min (or min stack is empty). When popping, pop from min stack if the popped value equals the current min. getMin() just peeks the min stack.',
        hints: [
          'Use a second stack that only tracks minimums.',
          'Push to minStack when the new value is ≤ current minimum.',
          'Pop from minStack only when the main pop value equals current min.',
        ],
        timeComplexity: 'O(1) all operations',
        spaceComplexity: 'O(N)',
      },
      {
        id: 'sq-3',
        title: 'Sliding Window Maximum',
        difficulty: 'Hard',
        tags: ['Sliding Window', 'Deque', 'Queue'],
        problemStatement: 'You are given an array of integers nums, and a sliding window of size k which moves from the very left to the very right. Return an array of the maximum sliding window for each position.',
        approach: 'Use a monotonic deque (decreasing from front to back) storing indices. For each element: (1) Remove indices outside the window from the front. (2) Remove indices from the back while their values are less than current. (3) Add current index to the back. The front always has the window maximum.',
        hints: [
          'Use a deque storing indices in decreasing order of value.',
          'Remove elements outside the window from the front.',
          'Remove smaller elements from the back — they can never be a maximum.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(K)',
      },
    ],
  },
  {
    id: 'trees',
    title: 'Trees',
    icon: 'git-branch',
    color: '#8B5CF6',
    type: 'dsa',
    questions: [
      {
        id: 'tree-1',
        title: 'Maximum Depth of Binary Tree',
        difficulty: 'Easy',
        tags: ['Tree', 'DFS', 'BFS', 'Recursion'],
        problemStatement: 'Given the root of a binary tree, return its maximum depth. A binary tree\'s maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.',
        approach: 'Recursive DFS: maxDepth(node) = 1 + max(maxDepth(left), maxDepth(right)). Base case: null node returns 0. Alternatively, use BFS and count levels.',
        hints: [
          'Recursively: depth = 1 + max(leftDepth, rightDepth).',
          'Base case: null returns 0.',
          'BFS alternative: count levels, increment counter per level.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(H) where H is tree height',
      },
      {
        id: 'tree-2',
        title: 'Level Order Traversal',
        difficulty: 'Medium',
        tags: ['Tree', 'BFS', 'Queue'],
        problemStatement: 'Given the root of a binary tree, return the level order traversal of its nodes\' values (i.e., from left to right, level by level).',
        approach: 'Use a queue (BFS). Start with root. For each level: record current queue length, process exactly that many nodes (adding their children), and collect node values into a level array. Append level array to result.',
        hints: [
          'BFS with a queue is the natural fit.',
          'At each level, snapshot the queue length first.',
          'Process exactly that many nodes, push children for the next level.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(N)',
      },
      {
        id: 'tree-3',
        title: 'Lowest Common Ancestor',
        difficulty: 'Medium',
        tags: ['Tree', 'DFS', 'Recursion'],
        problemStatement: 'Given a binary tree, find the lowest common ancestor (LCA) of two given nodes p and q. The LCA is defined as the lowest node in the tree that has both p and q as descendants (a node can be a descendant of itself).',
        approach: 'Recursive DFS: if current node is null, p, or q, return it. Recurse left and right. If both return non-null, current node is the LCA. If only one returns non-null, that is the LCA (both nodes are in that subtree).',
        hints: [
          'If root is p or q, root is the LCA.',
          'Search left and right subtrees recursively.',
          'If both sides return non-null, current node is the LCA.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(H)',
      },
      {
        id: 'tree-4',
        title: 'Binary Tree Maximum Path Sum',
        difficulty: 'Hard',
        tags: ['Tree', 'DFS', 'Dynamic Programming'],
        problemStatement: 'A path in a binary tree is a sequence of nodes where each pair of adjacent nodes in the sequence has an edge connecting them. A node can only appear in the sequence at most once. The path does not need to pass through the root. Given the root of a binary tree, return the maximum path sum.',
        approach: 'For each node, compute the max gain from left and right subtrees (clamped to 0 if negative). The path through this node has sum = node.val + leftGain + rightGain — update global max. Return node.val + max(leftGain, rightGain) to the parent (a path through a node can only go one direction up).',
        hints: [
          'Each node computes its contribution to paths passing through it.',
          'Left and right gains are clamped to 0 (ignore negative subtrees).',
          'A path through node = node.val + leftGain + rightGain — update global max.',
          'Return to parent: node.val + max(leftGain, rightGain) — only one branch goes up.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(H)',
      },
    ],
  },
  {
    id: 'bst',
    title: 'BST',
    icon: 'share-2',
    color: '#06B6D4',
    type: 'dsa',
    questions: [
      {
        id: 'bst-1',
        title: 'Validate Binary Search Tree',
        difficulty: 'Medium',
        tags: ['BST', 'DFS', 'Inorder'],
        problemStatement: 'Given the root of a binary tree, determine if it is a valid binary search tree (BST). A valid BST requires: left subtree values are strictly less than the node, right subtree values are strictly greater, and both subtrees are themselves valid BSTs.',
        approach: 'Pass min and max bounds to each recursive call. Root has bounds (-Infinity, +Infinity). Left child inherits (min, node.val), right child inherits (node.val, max). If any node violates its bounds, return false. Alternatively, do inorder traversal and verify values are strictly increasing.',
        hints: [
          'Pass valid (min, max) range to each recursive call.',
          'Left subtree: range becomes (min, current.val).',
          'Right subtree: range becomes (current.val, max).',
          'Inorder traversal must be strictly increasing.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(H)',
      },
      {
        id: 'bst-2',
        title: 'Kth Smallest Element in a BST',
        difficulty: 'Medium',
        tags: ['BST', 'Inorder', 'DFS'],
        problemStatement: 'Given the root of a binary search tree and an integer k, return the kth smallest value (1-indexed) of all the values of the nodes in the tree.',
        approach: 'Inorder traversal of a BST yields values in sorted ascending order. Do iterative inorder traversal, counting nodes visited. When count reaches k, return the current node\'s value. Iterative approach uses a stack and is straightforward.',
        hints: [
          'Inorder traversal (left, root, right) gives sorted order in a BST.',
          'Count nodes visited — return when count equals k.',
          'Use iterative inorder with a stack for clean implementation.',
        ],
        timeComplexity: 'O(H + K)',
        spaceComplexity: 'O(H)',
      },
    ],
  },
  {
    id: 'graphs',
    title: 'Graphs',
    icon: 'share-2',
    color: '#F97316',
    type: 'dsa',
    questions: [
      {
        id: 'graph-1',
        title: 'Number of Islands',
        difficulty: 'Medium',
        tags: ['Graph', 'DFS', 'BFS', 'Union-Find'],
        problemStatement: 'Given an m×n 2D binary grid where \'1\' represents land and \'0\' represents water, return the number of islands. An island is surrounded by water and formed by connecting adjacent lands horizontally or vertically.',
        approach: 'DFS/BFS approach: scan grid left-to-right, top-to-bottom. When a \'1\' is found, increment counter, then DFS/BFS to mark all connected \'1\'s as visited (set to \'0\'). Count how many times DFS is initiated.',
        hints: [
          'Start a DFS whenever you find an unvisited \'1\'.',
          'Mark all connected land as visited to avoid recounting.',
          'Count the number of DFS initiations.',
        ],
        timeComplexity: 'O(M × N)',
        spaceComplexity: 'O(M × N)',
      },
      {
        id: 'graph-2',
        title: 'Course Schedule (Cycle Detection)',
        difficulty: 'Medium',
        tags: ['Graph', 'Topological Sort', 'DFS'],
        problemStatement: 'There are numCourses courses (0 to numCourses-1). Given an array of prerequisites where prerequisites[i] = [a, b] means you must take b before a, determine if you can finish all courses.',
        approach: 'Model as a directed graph and detect cycles using DFS with 3-color marking: unvisited (0), in-progress (1), done (2). If DFS revisits an in-progress node, a cycle exists → return false. If all nodes finish without cycle → return true. Alternatively, use Kahn\'s BFS topological sort.',
        hints: [
          'Model as directed graph: prerequisite → course.',
          'A cycle in the graph means courses cannot all be completed.',
          'Use DFS with 3 states: unvisited, visiting, visited.',
          'Visiting a "visiting" node means a cycle exists.',
        ],
        timeComplexity: 'O(V + E)',
        spaceComplexity: 'O(V + E)',
      },
      {
        id: 'graph-3',
        title: 'Word Ladder',
        difficulty: 'Hard',
        tags: ['Graph', 'BFS', 'String'],
        problemStatement: 'A transformation sequence from word beginWord to endWord using a dictionary wordList is a sequence where each adjacent pair of words differs by a single letter and each intermediate word must be in wordList. Given beginWord, endWord, and wordList, return the number of words in the shortest transformation sequence, or 0 if impossible.',
        approach: 'BFS from beginWord. At each step, try all single-character mutations of the current word. If the mutation exists in the word set, add it to the queue and remove from the set to avoid revisiting. Return level count when endWord is reached.',
        hints: [
          'BFS gives the shortest path.',
          'Generate all 26-letter mutations of each word.',
          'Use a set for O(1) word lookup and remove visited words.',
        ],
        timeComplexity: 'O(N × L × 26) where N is wordList size, L is word length',
        spaceComplexity: 'O(N × L)',
      },
    ],
  },
  {
    id: 'heap',
    title: 'Heap',
    icon: 'triangle',
    color: '#EC4899',
    type: 'dsa',
    questions: [
      {
        id: 'heap-1',
        title: 'Top K Frequent Elements',
        difficulty: 'Medium',
        tags: ['Heap', 'HashMap', 'Bucket Sort'],
        problemStatement: 'Given an integer array nums and an integer k, return the k most frequent elements. You may return the answer in any order.',
        approach: 'Count frequencies with a HashMap, then use a min-heap of size k: push each (count, num). When heap size exceeds k, pop (removes the least frequent). Result is the heap contents. Alternative O(N) approach: bucket sort by frequency, collect from highest buckets.',
        hints: [
          'Count frequencies first with a HashMap.',
          'Min-heap of size k: always keep the k largest frequencies.',
          'Bucket sort alternative: bucket index = frequency, collect top k from high to low.',
        ],
        timeComplexity: 'O(N log K)',
        spaceComplexity: 'O(N + K)',
      },
      {
        id: 'heap-2',
        title: 'Find Median from Data Stream',
        difficulty: 'Hard',
        tags: ['Heap', 'Design', 'Two Heaps'],
        problemStatement: 'Implement a data structure that supports adding integers from a data stream and finding the median of all elements so far. Implement MedianFinder with addNum(int num) and findMedian() → double.',
        approach: 'Maintain two heaps: a max-heap (lower half) and a min-heap (upper half). After each insertion, rebalance so they differ by at most 1 element. Median is the top of the larger heap (odd count) or average of both tops (even count).',
        hints: [
          'Lower half: max-heap. Upper half: min-heap.',
          'Always maintain |maxHeap.size - minHeap.size| ≤ 1.',
          'Median: top of larger heap, or average of both tops.',
        ],
        timeComplexity: 'O(log N) add, O(1) median',
        spaceComplexity: 'O(N)',
      },
    ],
  },
  {
    id: 'hashmap',
    title: 'HashMap',
    icon: 'hash',
    color: '#14B8A6',
    type: 'dsa',
    questions: [
      {
        id: 'hm-1',
        title: 'LRU Cache',
        difficulty: 'Medium',
        tags: ['HashMap', 'Doubly Linked List', 'Design'],
        problemStatement: 'Design a data structure that follows the constraints of a Least Recently Used (LRU) cache. Implement the LRUCache class with get(key) and put(key, value), both in O(1) time. When capacity is exceeded, evict the least recently used key.',
        approach: 'Combine a HashMap (key → node) with a Doubly Linked List (maintains access order). On get or put, move the node to the front (most recently used). On capacity overflow, remove from the back (least recently used). Dummy head/tail nodes simplify edge cases.',
        hints: [
          'HashMap for O(1) key lookup.',
          'Doubly linked list for O(1) insertion/deletion to maintain order.',
          'Most recently used at head, least at tail.',
          'Dummy head and tail nodes simplify pointer logic.',
        ],
        timeComplexity: 'O(1) for get and put',
        spaceComplexity: 'O(capacity)',
      },
    ],
  },
  {
    id: 'sliding-window',
    title: 'Sliding Window',
    icon: 'maximize-2',
    color: '#6366F1',
    type: 'dsa',
    questions: [
      {
        id: 'sw-1',
        title: 'Longest Repeating Character Replacement',
        difficulty: 'Medium',
        tags: ['Sliding Window', 'String'],
        problemStatement: 'You are given a string s and an integer k. You can choose any character of the string and change it to any other uppercase English character. You can perform this operation at most k times. Return the length of the longest substring containing the same letter you can get after performing the above operations.',
        approach: 'Sliding window tracking character counts. A window is valid if (windowSize - maxCount) ≤ k, where maxCount is the count of the most frequent char in the window. Expand right always; shrink left when the window becomes invalid.',
        hints: [
          'Window is valid when (size - max_char_count) ≤ k.',
          'Expand right unconditionally; shrink left only when invalid.',
          'You don\'t need to recompute maxCount when shrinking — just track the max seen.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(1) — only 26 chars',
      },
      {
        id: 'sw-2',
        title: 'Permutation in String',
        difficulty: 'Medium',
        tags: ['Sliding Window', 'String', 'HashMap'],
        problemStatement: 'Given two strings s1 and s2, return true if s2 contains a permutation of s1. In other words, return true if one of s1\'s permutations is a substring of s2.',
        approach: 'Fixed-size sliding window of size len(s1). Maintain character frequency counts for s1 and the current window. Slide the window by adding the rightmost char and removing the leftmost char. Check if both frequency maps are equal.',
        hints: [
          'Fixed window size = len(s1).',
          'Use frequency count arrays of size 26.',
          'Slide by removing leftmost char and adding rightmost.',
          'Compare frequency arrays to check for a permutation match.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(1)',
      },
    ],
  },
  {
    id: 'two-pointers',
    title: 'Two Pointers',
    icon: 'chevrons-right',
    color: '#D946EF',
    type: 'dsa',
    questions: [
      {
        id: 'tp-1',
        title: 'Three Sum',
        difficulty: 'Medium',
        tags: ['Two Pointers', 'Array', 'Sorting'],
        problemStatement: 'Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i, j, and k are all different, and nums[i] + nums[j] + nums[k] == 0. The solution must not contain duplicate triplets.',
        approach: 'Sort the array. For each element nums[i] (the anchor), use two pointers (left = i+1, right = end) to find pairs that sum to -nums[i]. Skip duplicate values for the anchor and for left/right pointers to avoid duplicate triplets.',
        hints: [
          'Sort first — this enables two pointers and duplicate skipping.',
          'Fix one element, use two pointers for the remaining two.',
          'Skip duplicates: same anchor value, same left/right after a match.',
        ],
        timeComplexity: 'O(N²)',
        spaceComplexity: 'O(1) excluding output',
      },
    ],
  },
  {
    id: 'greedy',
    title: 'Greedy',
    icon: 'zap',
    color: '#84CC16',
    type: 'dsa',
    questions: [
      {
        id: 'gr-1',
        title: 'Jump Game',
        difficulty: 'Medium',
        tags: ['Greedy', 'Array'],
        problemStatement: 'You are given an integer array nums where nums[i] is the maximum jump length at position i. Return true if you can reach the last index, or false otherwise.',
        approach: 'Track the maximum reachable index as you iterate. At each position i, if i > maxReach, you cannot proceed (return false). Otherwise update maxReach = max(maxReach, i + nums[i]). If you complete the loop, return true.',
        hints: [
          'Track the furthest index reachable so far.',
          'If current index exceeds maxReach, return false.',
          'Update maxReach = max(maxReach, i + nums[i]) at each step.',
        ],
        timeComplexity: 'O(N)',
        spaceComplexity: 'O(1)',
      },
      {
        id: 'gr-2',
        title: 'Meeting Rooms II',
        difficulty: 'Medium',
        tags: ['Greedy', 'Heap', 'Sorting'],
        problemStatement: 'Given an array of meeting time intervals where intervals[i] = [start, end], return the minimum number of conference rooms required.',
        approach: 'Sort by start time. Use a min-heap of end times. For each meeting: if its start ≥ heap minimum (earliest ending room), pop and reuse the room. Always push current end time. The heap size at the end equals the number of rooms needed.',
        hints: [
          'Sort meetings by start time.',
          'Min-heap tracks when each room becomes free (end times).',
          'If new meeting starts ≥ earliest end, reuse that room (pop, push new end).',
          'Otherwise, allocate a new room (just push new end).',
        ],
        timeComplexity: 'O(N log N)',
        spaceComplexity: 'O(N)',
      },
    ],
  },
  {
    id: 'dp',
    title: 'Dynamic Programming',
    icon: 'cpu',
    color: '#0EA5E9',
    type: 'dsa',
    questions: [
      {
        id: 'dp-1',
        title: 'Coin Change',
        difficulty: 'Medium',
        tags: ['DP', 'BFS'],
        problemStatement: 'You are given an integer array coins representing coins of different denominations and an integer amount. Return the fewest number of coins needed to make up that amount. Return -1 if it cannot be achieved.',
        approach: 'Bottom-up DP: dp[0] = 0, dp[i] = min over each coin c of (dp[i - c] + 1) if i ≥ c. Initialize all dp values to amount+1 (infinity). Answer is dp[amount], or -1 if still "infinity".',
        hints: [
          'dp[i] = minimum coins to make amount i.',
          'For each amount, try every coin: dp[i] = min(dp[i], dp[i-coin] + 1).',
          'Initialize dp with a value larger than any valid answer (amount+1).',
        ],
        timeComplexity: 'O(amount × coins)',
        spaceComplexity: 'O(amount)',
      },
      {
        id: 'dp-2',
        title: 'Longest Common Subsequence',
        difficulty: 'Medium',
        tags: ['DP', 'String'],
        problemStatement: 'Given two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0.',
        approach: 'Build a 2D dp table where dp[i][j] = LCS length of text1[0..i-1] and text2[0..j-1]. If characters match: dp[i][j] = dp[i-1][j-1] + 1. Else: dp[i][j] = max(dp[i-1][j], dp[i][j-1]). Answer is dp[m][n].',
        hints: [
          'dp[i][j] = LCS length of first i chars of text1 and first j of text2.',
          'If chars match: dp[i][j] = dp[i-1][j-1] + 1.',
          'Else: dp[i][j] = max(dp[i-1][j], dp[i][j-1]).',
        ],
        timeComplexity: 'O(M × N)',
        spaceComplexity: 'O(M × N)',
      },
      {
        id: 'dp-3',
        title: 'Word Break',
        difficulty: 'Medium',
        tags: ['DP', 'String', 'Trie'],
        problemStatement: 'Given a string s and a dictionary of strings wordDict, return true if s can be segmented into a space-separated sequence of one or more dictionary words.',
        approach: 'Bottom-up DP: dp[i] = true if s[0..i-1] can be segmented. dp[0] = true (empty string). For each position i, check all j < i: if dp[j] is true and s[j..i-1] is in the dictionary, set dp[i] = true.',
        hints: [
          'dp[i] = can s[0..i] be segmented.',
          'For each i, try all j < i where dp[j] is true.',
          'Check if s[j..i] is in the word set.',
          'Use a Set for O(1) word lookup.',
        ],
        timeComplexity: 'O(N³) naive, O(N²) with set',
        spaceComplexity: 'O(N)',
      },
    ],
  },
  {
    id: 'backtracking',
    title: 'Backtracking',
    icon: 'refresh-cw',
    color: '#F59E0B',
    type: 'dsa',
    questions: [
      {
        id: 'bt-1',
        title: 'Letter Combinations of a Phone Number',
        difficulty: 'Medium',
        tags: ['Backtracking', 'String'],
        problemStatement: 'Given a string containing digits from 2-9, return all possible letter combinations that the number could represent (phone keyboard mapping). Return an empty list if the input is empty.',
        approach: 'Backtracking: at each digit, try all mapped letters, recurse for the next digit, backtrack. Base case: current combination length equals digits length — add to result.',
        hints: [
          'Map each digit to its phone letters.',
          'Backtrack: try each letter for current digit, recurse, undo.',
          'When combination length = digits length, record the result.',
        ],
        timeComplexity: 'O(4^N × N)',
        spaceComplexity: 'O(N)',
      },
      {
        id: 'bt-2',
        title: 'N-Queens',
        difficulty: 'Hard',
        tags: ['Backtracking'],
        problemStatement: 'The n-queens puzzle is the problem of placing n queens on an n×n chessboard so that no two queens attack each other. Given an integer n, return all distinct solutions. Each solution is a board configuration.',
        approach: 'Place one queen per row. For each row, try each column. Use sets to track: occupied columns, diagonals (row-col is constant on a diagonal), and anti-diagonals (row+col is constant). If column/diagonals are free, place queen and recurse to next row. Backtrack by removing from sets.',
        hints: [
          'Place one queen per row — reduces search space to N! instead of N^(2N).',
          'Three sets: columns, diagonals (r-c), anti-diagonals (r+c).',
          'Check all three sets before placing; remove from all three when backtracking.',
        ],
        timeComplexity: 'O(N!)',
        spaceComplexity: 'O(N)',
      },
    ],
  },
  {
    id: 'tries',
    title: 'Tries',
    icon: 'align-left',
    color: '#64748B',
    type: 'dsa',
    questions: [
      {
        id: 'trie-1',
        title: 'Implement Trie (Prefix Tree)',
        difficulty: 'Medium',
        tags: ['Trie', 'Design'],
        problemStatement: 'A trie (pronounced "try") or prefix tree is a tree data structure used to efficiently store and retrieve keys in a dataset of strings. Implement a Trie with insert(word), search(word), and startsWith(prefix) — all should run in O(L) where L is word length.',
        approach: 'Each TrieNode has a map of children (char → TrieNode) and a boolean isEndOfWord. insert: walk/create nodes for each char, mark last as end. search: walk nodes, return false if missing, check isEndOfWord. startsWith: walk nodes, return false if missing, return true at end.',
        hints: [
          'Each node has children (map or array of 26) and isEnd flag.',
          'Insert: create nodes as needed, mark last node as word end.',
          'Search: traverse and check isEnd. startsWith: just traverse.',
        ],
        timeComplexity: 'O(L) per operation',
        spaceComplexity: 'O(total chars inserted)',
      },
      {
        id: 'trie-2',
        title: 'Word Search II',
        difficulty: 'Hard',
        tags: ['Trie', 'Backtracking', 'DFS'],
        problemStatement: 'Given an m×n board of characters and a list of words, return all words on the board. Each word must be constructed from sequentially adjacent cells (horizontally or vertically). The same cell may not be used more than once in a word.',
        approach: 'Build a Trie from all words. DFS from each cell: at each step follow the Trie node for the current character. If a Trie node marks a word end, add to results. Mark cells visited during DFS and unmark on backtrack. Prune Trie nodes once a word is found to avoid duplicates.',
        hints: [
          'Build a Trie from all words for efficient prefix checking.',
          'DFS on the board, following the Trie simultaneously.',
          'Mark cells visited; unmark on backtrack.',
          'Remove found words from Trie to avoid duplicates.',
        ],
        timeComplexity: 'O(M×N×4^L)',
        spaceComplexity: 'O(total word chars)',
      },
    ],
  },
];

export const LLD_CATEGORIES: PracticeCategory[] = [
  {
    id: 'parking-lot',
    title: 'Parking Lot',
    icon: 'square',
    color: '#3B82F6',
    type: 'lld',
    questions: [
      {
        id: 'lld-parking-1',
        title: 'Design a Parking Lot System',
        difficulty: 'Medium',
        tags: ['OOP', 'Design Patterns', 'LLD'],
        problemStatement: 'Design a parking lot with multiple floors and spot types (compact, large, motorcycle). Support entry/exit, finding available spots, ticketing, and fee calculation based on duration. Handle concurrent access by multiple vehicles.',
        approach: 'Classes: ParkingLot (singleton), ParkingFloor, ParkingSpot (subclasses: CompactSpot, LargeSpot, BikeSpot), Vehicle (subclasses: Car, Truck, Bike), Ticket, ParkingAttendant, FeeCalculator. Use Strategy pattern for fee calculation. Each spot has isAvailable flag. Use a map of spotType → available spots for O(1) lookup.',
        hints: [
          'Identify main entities: Lot, Floor, Spot, Vehicle, Ticket.',
          'Use inheritance: Spot → Compact/Large/Bike; Vehicle → Car/Truck/Bike.',
          'Strategy pattern for different pricing models.',
          'Singleton for ParkingLot; Observer for display boards.',
        ],
        timeComplexity: 'O(1) for spot lookup with a free-spot map',
        spaceComplexity: 'O(total spots)',
      },
    ],
  },
  {
    id: 'elevator',
    title: 'Elevator System',
    icon: 'arrow-up',
    color: '#8B5CF6',
    type: 'lld',
    questions: [
      {
        id: 'lld-elevator-1',
        title: 'Design an Elevator System',
        difficulty: 'Hard',
        tags: ['OOP', 'State Machine', 'Scheduling', 'LLD'],
        problemStatement: 'Design an elevator system for a building with multiple floors and elevators. Support pressing buttons from floors and inside elevators. Implement an efficient dispatch algorithm (LOOK or SCAN) to assign elevators to floor requests. Handle door open/close and overload scenarios.',
        approach: 'Classes: ElevatorSystem (dispatcher), Elevator (state machine: IDLE/MOVING_UP/MOVING_DOWN), ElevatorButton, HallButton, Request, Floor. State machine per elevator: tracks current floor, direction, destination queue. LOOK algorithm: scan in one direction, reverse only when no more requests in that direction. Observer pattern for button presses.',
        hints: [
          'Elevator has states: IDLE, MOVING_UP, MOVING_DOWN.',
          'LOOK algorithm: service requests in current direction, then reverse.',
          'Separate internal requests (inside elevator) from external (floor buttons).',
          'Dispatcher assigns closest idle elevator or one already heading that way.',
        ],
        timeComplexity: 'O(N) per dispatch where N = number of elevators',
        spaceComplexity: 'O(floors × elevators)',
      },
    ],
  },
  {
    id: 'atm',
    title: 'ATM',
    icon: 'credit-card',
    color: '#10B981',
    type: 'lld',
    questions: [
      {
        id: 'lld-atm-1',
        title: 'Design an ATM',
        difficulty: 'Medium',
        tags: ['OOP', 'State Machine', 'LLD'],
        problemStatement: 'Design an ATM machine that supports card insertion, PIN verification, balance inquiry, cash withdrawal, and deposit. Model the states of the ATM, handle insufficient funds, and maintain account integrity for concurrent access.',
        approach: 'State Machine with states: IDLE, CARD_INSERTED, AUTHENTICATED, TRANSACTION, DISPENSING. Classes: ATM (state machine), Card, Account, CashDispenser (denominations using greedy), Transaction, Bank (interface), Screen. State transitions: insertCard → enterPIN → selectTransaction → execute → ejectCard. Use Template Method for transaction types.',
        hints: [
          'ATM is a state machine: IDLE → CARD_INSERTED → AUTHENTICATED → TRANSACTION.',
          'CashDispenser uses greedy (largest bills first) for dispensing.',
          'Bank interface decouples ATM from specific bank implementations.',
          'Each state handles valid transitions and rejects invalid operations.',
        ],
        timeComplexity: 'O(D) for dispensing where D = number of denominations',
        spaceComplexity: 'O(D) for cash inventory',
      },
    ],
  },
  {
    id: 'splitwise',
    title: 'Splitwise',
    icon: 'divide-circle',
    color: '#EF4444',
    type: 'lld',
    questions: [
      {
        id: 'lld-splitwise-1',
        title: 'Design Splitwise',
        difficulty: 'Hard',
        tags: ['OOP', 'Graph', 'Debt Simplification', 'LLD'],
        problemStatement: 'Design a bill-splitting app like Splitwise. Users can create groups, add expenses (split equally, by percentage, or by exact amount), view who owes whom, settle debts, and simplify debts (minimize the number of transactions to settle all debts).',
        approach: 'Classes: User, Group, Expense, Split (subclasses: EqualSplit, PercentageSplit, ExactSplit), ExpenseManager, Balance. Debt simplification: compute net balance per user, use min-heap of creditors and max-heap of debtors, greedily match the largest debtor with largest creditor. Strategy pattern for split types.',
        hints: [
          'Three split types: Equal, Percentage, Exact — use Strategy/inheritance.',
          'Store balances as a map: User → map of (who owes them → amount).',
          'Debt simplification: net balance per user, then greedy two-heap matching.',
          'Validate that percentages sum to 100%, exact amounts sum to total.',
        ],
        timeComplexity: 'O(N log N) for debt simplification',
        spaceComplexity: 'O(N²) for pairwise balances',
      },
    ],
  },
  {
    id: 'bookmyshow',
    title: 'BookMyShow',
    icon: 'film',
    color: '#F59E0B',
    type: 'lld',
    questions: [
      {
        id: 'lld-bms-1',
        title: 'Design BookMyShow (Ticket Booking)',
        difficulty: 'Hard',
        tags: ['OOP', 'Concurrency', 'Booking', 'LLD'],
        problemStatement: 'Design an online ticket booking system like BookMyShow. Support movies, theaters, shows (date/time), seat selection, booking, cancellation, and payment. Handle concurrent seat reservations to prevent double-booking.',
        approach: 'Classes: Movie, Theater, Show, Seat (AVAILABLE/LOCKED/BOOKED), Booking, Payment, User, Notification. Seat locking: use a time-limited lock (5-min reservation before payment). Concurrency: optimistic locking with DB versioning or pessimistic lock on seat rows. Payment: async with state machine (PENDING/PROCESSING/COMPLETED/FAILED).',
        hints: [
          'Seat states: AVAILABLE → LOCKED (temp) → BOOKED or AVAILABLE (timeout).',
          'Locking seats for a time window prevents double-booking during checkout.',
          'Search: filter by city → theater → movie → show.',
          'Observer for notifications: booking confirmation, cancellation.',
        ],
        timeComplexity: 'O(seats) for seat selection',
        spaceComplexity: 'O(shows × seats)',
      },
    ],
  },
  {
    id: 'snake-ladder',
    title: 'Snake & Ladder',
    icon: 'activity',
    color: '#06B6D4',
    type: 'lld',
    questions: [
      {
        id: 'lld-snake-1',
        title: 'Design Snake and Ladder Game',
        difficulty: 'Easy',
        tags: ['OOP', 'Game Design', 'LLD'],
        problemStatement: 'Design the Snake and Ladder board game for multiple players. Support customizable board size, placement of snakes and ladders, dice rolling, turn management, and win detection. Players take turns rolling dice and moving accordingly.',
        approach: 'Classes: Game, Board, Cell, Snake, Ladder, Player, Dice. Board initializes cells with their snake/ladder connections (using a Map<position, newPosition>). Game loop: roll dice, move player, apply cell effect, check win. Dice can be abstracted for testability (DiceStrategy for different dice types).',
        hints: [
          'Board is a 1D array; Cell stores snake/ladder destination if any.',
          'Map<int, int> for jumps: key=start, value=destination (works for both snakes and ladders).',
          'Game loop: roll → new position = current + roll → apply jump if exists → check win.',
          'Separate Dice as injectable dependency for testability.',
        ],
        timeComplexity: 'O(1) per move',
        spaceComplexity: 'O(N²) for N×N board',
      },
    ],
  },
  {
    id: 'chess',
    title: 'Chess',
    icon: 'flag',
    color: '#64748B',
    type: 'lld',
    questions: [
      {
        id: 'lld-chess-1',
        title: 'Design a Chess Game',
        difficulty: 'Hard',
        tags: ['OOP', 'Game Design', 'Polymorphism', 'LLD'],
        problemStatement: 'Design a two-player Chess game. Model all pieces with their movement rules, handle turn management, check/checkmate detection, castling, en passant, and pawn promotion.',
        approach: 'Classes: ChessGame, Board (8×8 Cell[][]), Cell, Piece (abstract, subclasses: King, Queen, Rook, Bishop, Knight, Pawn), Player, Move. Each Piece implements getValidMoves(board). Check detection: after any move, verify if the current player\'s king is under attack. Checkmate: no valid moves that resolve check. Use Command pattern for move history (enables undo).',
        hints: [
          'Piece hierarchy: abstract Piece with getValidMoves() method.',
          'Each piece knows its movement rules; Board handles legality (bounds, blocking).',
          'After every move, check if current player\'s king is in check.',
          'Command pattern: store moves as objects for history and undo.',
        ],
        timeComplexity: 'O(N²) per move validation where N=8',
        spaceComplexity: 'O(N²) for board',
      },
    ],
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic Tac Toe',
    icon: 'x',
    color: '#EC4899',
    type: 'lld',
    questions: [
      {
        id: 'lld-ttt-1',
        title: 'Design Tic Tac Toe',
        difficulty: 'Easy',
        tags: ['OOP', 'Game Design', 'LLD'],
        problemStatement: 'Design a generalized Tic Tac Toe game for N×N board and K players. Support making moves, win detection, draw detection, and the ability to extend to larger boards.',
        approach: 'Classes: TicTacToe, Board, Player, Symbol. Win detection optimization: instead of scanning full board after each move, maintain row counts, col counts, and diagonal counts per player. A player wins when any count reaches N. O(1) win check per move.',
        hints: [
          'Maintain row[player][row], col[player][col], diag[player], antiDiag[player] counts.',
          'After each move, increment counts for the moved row/col/diagonal.',
          'Win when any count reaches N.',
          'Draw when all cells are filled with no winner.',
        ],
        timeComplexity: 'O(1) per move for win detection',
        spaceComplexity: 'O(N × Players)',
      },
    ],
  },
  {
    id: 'logger',
    title: 'Logger',
    icon: 'terminal',
    color: '#84CC16',
    type: 'lld',
    questions: [
      {
        id: 'lld-logger-1',
        title: 'Design a Logger / Logging Framework',
        difficulty: 'Medium',
        tags: ['OOP', 'Design Patterns', 'LLD'],
        problemStatement: 'Design a flexible logging framework that supports multiple log levels (DEBUG, INFO, WARN, ERROR), multiple output destinations (console, file, remote server), log formatting, filtering, and minimal performance impact on the calling application.',
        approach: 'Classes: Logger (singleton or factory), LogLevel (enum), LogRecord, Appender interface (ConsoleAppender, FileAppender, RemoteAppender), Formatter interface (PlainTextFormatter, JSONFormatter), Filter. Chain of Responsibility pattern for chaining appenders. Log record contains: level, message, timestamp, thread, class name. Async logging with a bounded queue for performance.',
        hints: [
          'Logger is typically a singleton (or use Logger.getLogger(class)).',
          'Appender interface separates output destinations from logging logic.',
          'Chain of Responsibility: each appender can pass log to next.',
          'Async: log to a queue, background thread drains to actual appenders.',
        ],
        timeComplexity: 'O(1) for async logging (queue insert)',
        spaceComplexity: 'O(queue capacity)',
      },
    ],
  },
  {
    id: 'rate-limiter',
    title: 'Rate Limiter',
    icon: 'shield',
    color: '#F97316',
    type: 'lld',
    questions: [
      {
        id: 'lld-rl-1',
        title: 'Design a Rate Limiter',
        difficulty: 'Hard',
        tags: ['OOP', 'System Design', 'Concurrency', 'LLD'],
        problemStatement: 'Design a rate limiter that limits the number of requests a user can make in a given time window. Support multiple strategies: fixed window, sliding window, token bucket, and leaky bucket. Should work for high-throughput distributed systems.',
        approach: 'Interface RateLimiter with isAllowed(userId). Implementations:\n• Fixed Window: Map<userId, count+windowStart>. Reset count on new window.\n• Sliding Window Log: sorted set of timestamps per user. Remove old, count remaining.\n• Token Bucket: Map<userId, (tokens, lastRefillTime)>. Refill tokens at fixed rate; consume 1 per request.\n• Leaky Bucket: queue per user, drain at fixed rate.',
        hints: [
          'Token bucket: tokens refill at rate R per second; each request costs 1 token.',
          'Sliding window: store request timestamps, evict those outside the window.',
          'For distributed: use Redis with atomic operations (INCR + TTL or Lua scripts).',
          'Token bucket is generally preferred: handles bursts gracefully.',
        ],
        timeComplexity: 'O(1) for token bucket, O(N) for sliding window log',
        spaceComplexity: 'O(users × window_requests)',
      },
    ],
  },
  {
    id: 'cache',
    title: 'Cache',
    icon: 'database',
    color: '#0EA5E9',
    type: 'lld',
    questions: [
      {
        id: 'lld-cache-1',
        title: 'Design a Distributed Cache',
        difficulty: 'Hard',
        tags: ['OOP', 'Cache', 'Eviction Policies', 'LLD'],
        problemStatement: 'Design a cache system with pluggable eviction policies (LRU, LFU, FIFO). Support get, put, and delete operations, TTL (time-to-live) for entries, and the ability to extend to a distributed setting (consistent hashing for sharding).',
        approach: 'Interface EvictionPolicy with evict() and keyAccessed(). Cache<K,V> delegates eviction to the policy (Strategy pattern). LRU: HashMap + Doubly Linked List. LFU: two HashMaps + min-heap or HashMap of frequency → DLL. TTL: background thread evicts expired entries or lazy eviction on access. For distributed: consistent hash ring maps keys to cache nodes.',
        hints: [
          'Strategy pattern for eviction: pass EvictionPolicy to Cache constructor.',
          'LRU = HashMap + Doubly Linked List; LFU = HashMap + frequency buckets.',
          'TTL lazy eviction: on get, check if expired; if so, remove and return null.',
          'Write-through vs write-back: write-through immediately syncs to backing store.',
        ],
        timeComplexity: 'O(1) for LRU get/put; O(log N) for LFU with heap',
        spaceComplexity: 'O(capacity)',
      },
    ],
  },
  {
    id: 'notification',
    title: 'Notification System',
    icon: 'bell',
    color: '#6366F1',
    type: 'lld',
    questions: [
      {
        id: 'lld-notif-1',
        title: 'Design a Notification System',
        difficulty: 'Hard',
        tags: ['OOP', 'Observer', 'Async', 'LLD'],
        problemStatement: 'Design a scalable notification system that sends notifications to users through multiple channels (push, email, SMS, in-app). Support user preferences (opt-in/out per channel), notification templates, retry on failure, rate limiting per user, and delivery receipts.',
        approach: 'Classes: NotificationService, NotificationChannel (interface, implementations: PushChannel, EmailChannel, SMSChannel), NotificationTemplate, UserPreference, Notification, NotificationStatus, RetryQueue. Observer pattern: events trigger notifications. Strategy for channels. Outbox pattern for reliability: write notification to DB first, background worker sends and updates status. Retry with exponential backoff.',
        hints: [
          'Check user preferences before sending on any channel.',
          'Observer/Event: business events emit notifications via an event bus.',
          'Outbox pattern: persist notification first, then send — ensures reliability.',
          'Retry with exponential backoff: 1s → 2s → 4s → ... up to max retries.',
        ],
        timeComplexity: 'O(channels) per notification',
        spaceComplexity: 'O(users × notifications)',
      },
    ],
  },
];

export const ALL_CATEGORIES = [...DSA_CATEGORIES, ...LLD_CATEGORIES];

export function getCategoryById(id: string): PracticeCategory | undefined {
  return ALL_CATEGORIES.find((c) => c.id === id);
}

export function getQuestionById(questionId: string): { question: PracticeQuestion; category: PracticeCategory } | undefined {
  for (const cat of ALL_CATEGORIES) {
    const q = cat.questions.find((q) => q.id === questionId);
    if (q) return { question: q, category: cat };
  }
  return undefined;
}

export const DIFFICULTY_ORDER = { Easy: 0, Medium: 1, Hard: 2 } as const;
