// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/interview-ace/Discuss.tsx": () => import("../components/mockups/interview-ace/Discuss.tsx"),
  "./components/mockups/interview-ace/Home.tsx": () => import("../components/mockups/interview-ace/Home.tsx"),
  "./components/mockups/interview-ace/Practice.tsx": () => import("../components/mockups/interview-ace/Practice.tsx"),
  "./components/mockups/interview-ace/Profile.tsx": () => import("../components/mockups/interview-ace/Profile.tsx"),
  "./components/mockups/interview-ace/TopicDetail.tsx": () => import("../components/mockups/interview-ace/TopicDetail.tsx")
};
